version: "3"
services:
  server:
    image: backend
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/infy22?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=infy22
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

networks:
  springmysql-net:
